name: Android Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual workflow runs from GitHub UI
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create gradle wrapper jar
      run: mkdir -p gradle/wrapper && curl -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.0.0/gradle/wrapper/gradle-wrapper.jar
      
    - name: Run static code analysis
      run: ./gradlew lint --stacktrace
      
    - name: Run Unit Tests
      run: ./gradlew test --stacktrace

    - name: Build Debug APK
      run: ./gradlew assembleDebug --info --stacktrace
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          app/build/reports/
          app/build/test-results/
          
    - name: Upload Lint Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: lint-reports
        path: app/build/reports/lint-results-debug.html
